### ISSUE TITLE
For flashing, do I need power from both PSU and ST-Link?

### ISSUE THREAD

**Issue by suit4** [jakplugg/Monsoon#3]

**Comment by suit4** [comment]
It looks like there already is a connection between the Eurorack power header and the JTAG pin for 3.3V. 

Do I need to connect both PSU to power header and ST-Link (clone) power line to JTAG power pin?

Or is power via JTAG header sufficient?

**Comment by AfterLaterAudio** [comment]
You need power through the power headers while flashing.

**Comment by suit4** [comment]
Yup. That worked nicely. Thanks
