### ISSUE TITLE
R73, R76, R79, R82 value?

### ISSUE THREAD

**Issue by 01tot10** [jakplugg/Monsoon#4]
Hey!

The BOM says 1.2k for R73, R76, R79, R82 but without Mouser reference, while on the schemo they're marked as 330R.
What would be there right value there? I'm leaning towards 330R here since they are for the LEDs.

**Comment by jakplugg** [comment]
It's up to your LED brightness preference, but i would go with 1.2k to
start with.

**Comment by 01tot10** [comment]
Thanks for the quick reply! Oh, my intuition was guiding me wrong then. Somehow it sounded like a large value for controlling the LEDs. Thanks for clearing that out, I'll close the issue.
